### ISSUE TITLE
UI still references removed setting to use internal memory

### ISSUE THREAD

**Issue by fschwiet** [flerda/Anki-Android#58]
From 01-core.html:

<string name="sd_card_not_mounted">SD card not mounted.\n\nYou can store your collection in the internal memory too, though it\'s not recommended as you cannot access the file that easily. You can activate this in the preferences (open them by touching this text).</string>

I am seeing a similar (if not the same) UI when I try to run AnkiDroid from source.  I guess my AVD is setup up wrong.  It seems the setting to use internal memory was removed (source: https://groups.google.com/d/msg/anki-android/7x2h_OBJQGk/bL5bho3i-2QJ) and so the UI should be updated not to reference this setting anymore.

**Comment by nicolas-raoul** [comment]
Hello fschwiet,
Could you please post this issue on our issue tracker at http://code.google.com/p/ankidroid/issues ?
Thanks for your feedback!

@flerda Could you please disable Github's issues feature as we did at https://github.com/ankidroid/Anki-Android and https://github.com/nicolas-raoul/Anki-Android ? Thanks! :-)

**Comment by fschwiet** [comment]
created https://code.google.com/p/ankidroid/issues/detail?id=2403&thanks=2403&ts=1415913598
